# Generated by Django 4.2.21 on 2025-06-23 15:34

from django.db import migrations, models
import doctor.validators


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='govt_id',
            field=models.FileField(upload_to='doctor_documents/govt_id/', validators=[doctor.validators.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='medical_certificate',
            field=models.FileField(upload_to='doctor_documents/medical_certificate/', validators=[doctor.validators.validate_document_file]),
        ),
    ]
