# Generated by Django 4.2.21 on 2025-06-24 14:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('mode', models.CharField(choices=[('online', 'Online'), ('in-person', 'In-Person')], default='online', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('no-show', 'No-Show')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctor.doctor')),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='doctor_appo_date_d93ed1_idx'), models.Index(fields=['status'], name='doctor_appo_status_b3bdeb_idx')],
            },
        ),
    ]
