# Generated by Django 4.2.21 on 2025-06-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
