# Generated by Django 4.2.21 on 2025-06-26 05:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_appointment_rejection_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('granted', 'Granted'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='doctor.doctor')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='doctor_cons_status_45be7a_idx'), models.Index(fields=['patient_id'], name='doctor_cons_patient_6ada0d_idx')],
                'unique_together': {('doctor', 'patient_id')},
            },
        ),
    ]
