# Generated by Django 4.2.21 on 2025-06-26 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0006_consent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reports', models.JSONField(blank=True, default=list)),
                ('vitals', models.JSONField(blank=True, default=dict)),
                ('prescriptions', models.JSONField(blank=True, default=list)),
                ('visits', models.JSONField(blank=True, default=list)),
                ('flags', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['patient_id'], name='doctor_pati_patient_096a44_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.UUIDField()),
                ('action', models.CharField(choices=[('viewed', 'Viewed')], default='viewed', max_length=10)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['patient_id'], name='doctor_acce_patient_1b1f6c_idx'), models.Index(fields=['accessed_at'], name='doctor_acce_accesse_04e756_idx')],
            },
        ),
    ]
