# Generated by Django 4.2.21 on 2025-07-11 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_patienthistory_accesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_notes', to='doctor.appointment')),
            ],
            options={
                'indexes': [models.Index(fields=['appointment'], name='doctor_medi_appoint_ec8742_idx'), models.Index(fields=['created_at'], name='doctor_medi_created_eaa9ed_idx')],
            },
        ),
    ]
