# Generated by Django 4.2.21 on 2025-07-11 04:40

from django.db import migrations, models
import django.db.models.deletion
import doctor.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_medicalnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('file', models.FileField(upload_to='prescriptions/%Y/%m/%d/', validators=[doctor.validators.validate_document_file])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctor.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctor.doctor')),
            ],
            options={
                'indexes': [models.Index(fields=['patient_id'], name='doctor_pres_patient_13e793_idx'), models.Index(fields=['timestamp'], name='doctor_pres_timesta_b5d44b_idx')],
            },
        ),
    ]
